[package]
name = "dna_iZCore"
description = "iZ.Life BOSS - The DNA Kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
tokio.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
ed25519-dalek = { version = "2.1", features = ["rand_core"] }
sysinfo = "0.30"
sha2 = "0.10"
hex = "0.4"
mac_address = "1.1"
libp2p = { version = "0.53", features = ["tcp", "noise", "yamux", "mdns", "gossipsub", "macros", "tokio"] }
totp-lite = "2.0"
clap = { version = "4.4", features = ["derive"] }
ratatui = "0.26"
crossterm = { version = "0.27", features = ["event"] }
futures = "0.3"
